In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#load dataset
df=pd.read_csv(r"C:/Users/User-PC/Downloads/Healthcare Cost & Insurance Analysis/cleaned_insurance_dataset.csv")
print(df)

      age  sex  bmi  children  smoker  charges  region_Northwest  \
0      19    0   28         0       1    16885             False
1      18    1   34         1       0     1726             False
2      28    1   33         3       0     4449             False
3      33    1   23         0       0    21984              True
4      32    1   29         0       0     3867              True
...   ...  ...  ...       ...     ...      ...               ...
1333   50    1   31         3       0    10601              True
1334   18    0   32         0       0     2206             False
1335   18    0   37         0       0     1630             False
1336   21    0   26         0       0     2008             False
1337   61    0   29         0       1    29141              True

      region_Southeast  region_Southwest
0                False              True
1                 True             False
2                 True             False
3                False             False
4                False             False
...                ...               ...
1333             False             False
1334             False             False
1335              True             False
1336             False              True
1337             False             False

[1338 rows x 9 columns]

In [9]:
print("Shape:",df.shape)
print("Samples ",df.sample(5))

Shape: (1338, 9)
Samples        age  sex  bmi  children  smoker  charges  region_Northwest  \
259    19    1   32         0       1    33750              True
477    25    1   36         0       0     2534              True
876    49    0   27         1       0    26140             False
46     18    0   39         2       0     3393             False
1128   34    1   33         1       0    14358             False

      region_Southeast  region_Southwest
259              False             False
477              False             False
876              False              True
46               False             False
1128             False              True

In [40]:
#Value Counts for Categorical Features
smoker_distribution=df['smoker'].value_counts()
print("Smoker Distribution", smoker_distribution)

childrens=df['children'].value_counts()
print("Children Distribution", childrens)

gender=df.groupby('sex')['age'].sum()
print("\nPatient's Gender\n", gender)

age=df['age'].value_counts()
print("\nAge Distribution\n", age)

bmi=df['bmi'].value_counts()
print("\nBMI Distribution\n", bmi)

Smoker Distribution smoker
0    1064
1     274
Name: count, dtype: int64
Children Distribution children
0    574
1    324
2    240
3    157
4     25
5     18
Name: count, dtype: int64

Patient's Gender
 sex
0    26151
1    26308
Name: age, dtype: int64

Age Distribution
 age
18    69
19    68
50    29
51    29
47    29
46    29
45    29
20    29
48    29
52    29
22    28
49    28
54    28
53    28
21    28
26    28
24    28
25    28
28    28
27    28
23    28
43    27
29    27
30    27
41    27
42    27
44    27
31    27
40    27
32    26
33    26
56    26
34    26
55    26
57    26
37    25
59    25
58    25
36    25
38    25
35    25
39    25
61    23
60    23
63    23
62    23
64    22
Name: count, dtype: int64

BMI Distribution
 bmi
30    102
28    101
32     83
33     77
34     77
31     76
29     70
26     70
36     63
27     62
25     62
37     58
24     57
23     50
35     45
38     38
40     35
22     35
39     26
20     24
21     23
41     19
42     16
18     11
43     10
17      9
19      8
44      6
47      6
45      6
48      4
46      4
53      2
16      1
49      1
50      1
Name: count, dtype: int64

In [36]:
#Age grorup with highest or lowest medical charges
age_group= df.nlargest(10,'charges')[['age','sex','bmi','children','smoker']]
print("\nAge group with highest charges:\n", age_group)

age_group2= df.nsmallest(10,'charges')[['age','sex','bmi','children','smoker']]
print("\nAge group with lowest charges:\n", age_group2)

Age group with highest charges:
       age  sex  bmi  children  smoker
543    54    0   47         0       1
1300   45    1   30         0       1
1230   52    1   34         3       1
577    31    0   38         1       1
819    33    0   36         0       1
1146   60    1   33         0       1
34     28    1   36         1       1
1241   64    1   37         2       1
1062   59    1   41         1       1
488    44    0   38         0       1

Age group with lowest charges:
       age  sex  bmi  children  smoker
940    18    1   23         0       0
808    18    1   30         0       0
663    18    1   34         0       0
1244   18    1   33         0       0
22     18    1   34         0       0
194    18    1   34         0       0
866    18    1   37         0       0
781    18    1   41         0       0
442    18    1   43         0       0
1317   18    1   53         0       0